// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Layout is the shared page shell: mobile viewport, stylesheet and a
// centred column. On a phone the column is the whole screen (the app is used
// on phones ~99% of the time); on a wider screen it stops at a readable
// width, so a row's name and quantity do not drift apart.
// htmxConfig keeps htmx's defaults but also swaps 422 replies, so validation
// errors show up in place (htmx ignores 4xx bodies by default), and lets the
// browser report empty required fields instead of silently not sending.
const htmxConfig = `{"reportValidityOfForms":true,"responseHandling":[{"code":"204","swap":false},{"code":"[23]..","swap":true},{"code":"422","swap":true,"error":true},{"code":"[45]..","swap":false,"error":true}]}`

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/view/layout.templ`, Line: 18, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " · Roundtrip</title><link rel=\"stylesheet\" href=\"/static/tailwind.css\"><meta name=\"htmx-config\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(htmxConfig)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/web/view/layout.templ`, Line: 20, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><script src=\"/static/htmx.min.js\" defer></script></head><body class=\"bg-slate-50 text-slate-900\"><main class=\"mx-auto max-w-2xl p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// cardClass is a white panel holding a list of items. On a phone it bleeds
// through the page's side padding (-mx-4) to the screen edges, so the list
// keeps the whole width and only its own small padding keeps text off the
// edge. From the sm breakpoint up, where the page is narrower than the
// screen, it sits inside the padding as a rounded card again.
const cardClass = "-mx-4 bg-white px-3 py-4 shadow-sm sm:mx-0 sm:rounded-lg sm:px-4"

// stickyHeaderClass keeps a page's title bar at the top of the screen while
// its long list scrolls underneath. It spans the page's side padding, so on
// a phone it reaches the screen edges like cardClass (on a wider screen it
// stays 16px wider than the cards, unseen since it matches the page). Its
// background is solid, so rows pass under it rather than showing through. It is kept to one or two short lines: on a phone with the
// keyboard open, every pixel it takes is a pixel less of the list.
const stickyHeaderClass = "sticky top-0 z-10 -mx-4 border-b border-slate-200 bg-slate-50 px-4 py-2"

var _ = templruntime.GeneratedTemplate
