// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_user.sql

package db

import (
	"context"
)

const getAppUser = `-- name: GetAppUser :one
SELECT id, name
FROM app_user
ORDER BY id
LIMIT 1
`

func (q *Queries) GetAppUser(ctx context.Context) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getAppUser)
	var i AppUser
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
