// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basic_item.sql

package db

import (
	"context"
)

const listBasicItems = `-- name: ListBasicItems :many

SELECT family_member_id, name, per_day, fixed
FROM basic_item
ORDER BY family_member_id, position
`

type ListBasicItemsRow struct {
	FamilyMemberID int64
	Name           string
	PerDay         int64
	Fixed          int64
}

// Keep query files ASCII-only (see sql/queries/item.sql).
// In the order a new trip's items are added: owner, then catalogue position.
// Includes the Family bucket, so it does not go through ListPeople.
func (q *Queries) ListBasicItems(ctx context.Context) ([]ListBasicItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBasicItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBasicItemsRow
	for rows.Next() {
		var i ListBasicItemsRow
		if err := rows.Scan(
			&i.FamilyMemberID,
			&i.Name,
			&i.PerDay,
			&i.Fixed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
