// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO item (trip_id, family_member_id, name, name_key, quantity)
VALUES (?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	TripID         int64
	FamilyMemberID int64
	Name           string
	NameKey        string
	Quantity       int64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.TripID,
		arg.FamilyMemberID,
		arg.Name,
		arg.NameKey,
		arg.Quantity,
	)
	return err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM item
WHERE id = ? AND trip_id = ?
RETURNING family_member_id
`

type DeleteItemParams struct {
	ID     int64
	TripID int64
}

// Scoped to the trip so an item can't be removed through another trip's URL.
func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteItem, arg.ID, arg.TripID)
	var family_member_id int64
	err := row.Scan(&family_member_id)
	return family_member_id, err
}

const listFamilyMembers = `-- name: ListFamilyMembers :many

SELECT id, name
FROM family_member
ORDER BY id
`

// Keep query files ASCII-only: a multi-byte character (even in a comment)
// made sqlc slice the following queries at the wrong offsets.
func (q *Queries) ListFamilyMembers(ctx context.Context) ([]FamilyMember, error) {
	rows, err := q.db.QueryContext(ctx, listFamilyMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FamilyMember
	for rows.Next() {
		var i FamilyMember
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemNames = `-- name: ListItemNames :many
SELECT CAST(MIN(name) AS TEXT) AS name
FROM item
GROUP BY name_key
ORDER BY name_key
`

// Names used on any trip, suggested when adding items so names get reused.
// One spelling per name ignoring case (Sunscreen and sunscreen become one).
func (q *Queries) ListItemNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listItemNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripItems = `-- name: ListTripItems :many
SELECT id, family_member_id, name, quantity
FROM item
WHERE trip_id = ?
ORDER BY id
`

type ListTripItemsRow struct {
	ID             int64
	FamilyMemberID int64
	Name           string
	Quantity       int64
}

func (q *Queries) ListTripItems(ctx context.Context, tripID int64) ([]ListTripItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTripItems, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripItemsRow
	for rows.Next() {
		var i ListTripItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyMemberID,
			&i.Name,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
