// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip.sql

package db

import (
	"context"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trip (destination, departure_date, duration_days)
VALUES (?, ?, ?)
RETURNING id
`

type CreateTripParams struct {
	Destination   string
	DepartureDate string
	DurationDays  int64
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTrip, arg.Destination, arg.DepartureDate, arg.DurationDays)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTrip = `-- name: GetTrip :one
SELECT id, destination, departure_date, duration_days
FROM trip
WHERE id = ?
`

func (q *Queries) GetTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Destination,
		&i.DepartureDate,
		&i.DurationDays,
	)
	return i, err
}

const listTrips = `-- name: ListTrips :many
SELECT id, destination, departure_date, duration_days
FROM trip
ORDER BY departure_date, id
`

func (q *Queries) ListTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Destination,
			&i.DepartureDate,
			&i.DurationDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
